use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'GTMAppAuth'
  pod 'Magpie/HIPAPI'
  pod 'SwiftDate', '~> 5.0'
end

def ios_pods
  platform :ios, '14.0'

  shared_pods
end

def mac_pods
  platform :macos, '10.15'

  shared_pods

  pod 'KeyboardShortcuts', '~> 0.6.0'
  pod 'Preferences', :git => 'https://github.com/Hipo/Preferences.git'
end

target 'zoom-scheduler' do
  ios_pods
end

target 'zoom-scheduler-dev' do
  ios_pods
end

target 'zoom-scheduler-mac' do
  mac_pods
end

target 'zoom-scheduler-mac-dev' do
  mac_pods
end
